sudo: required
services:
  - docker
language: bash
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=monstrenyatko/rpi-alpine
    - QEMU_VERSION=v2.9.1-1
script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # get qemu-arm-static binary
  - mkdir tmp
  - >
    pushd tmp &&
    curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/$QEMU_VERSION/qemu-arm-static.tar.gz &&
    tar xzf qemu-arm-static.tar.gz &&
    popd
  # build image
  - docker build -t $REPO:$COMMIT .
  # test image
  - docker run $REPO:$COMMIT uname -a
  # push image
  - >
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      TAG=$(grep "FROM " Dockerfile | sed 's/.*://')
      docker tag $REPO:$COMMIT $REPO:$TRAVIS_BUILD_NUMBER
      docker tag $REPO:$COMMIT $REPO:$TAG
      docker tag $REPO:$COMMIT $REPO:latest
      docker push $REPO:$TRAVIS_BUILD_NUMBER
      docker push $REPO:$TAG
      docker push $REPO:latest
    fi
notifications:
  email:
    on_success: change
    on_failure: always
